/**
 * Shared bikepark database (DACH focus) used by Park-Picker and Ride-Log.
 * Park ids are stable and referenced by ride.parkId.
 *
 * Live data comes from external sources at runtime:
 * - Weather: OpenWeatherMap (lib/weather.ts, needs EXPO_PUBLIC_OPENWEATHER_KEY)
 * - Lift status: scraped daily by GitHub Actions into the park_status table
 *   (supabase/scrape_park_status.mjs). liftStatus here is only the offline fallback.
 */

export type LiftStatus = 'open' | 'partial' | 'closed' | 'season_end' | 'unknown';

export interface Bikepark {
    id: string;
    name: string;
    region: string;
    country: string;
    lat: number;
    lon: number;
    website: string;
    trails: number;
    lifts: number;
    liftStatus: LiftStatus;
    openLifts: number;
}

// Curated bikepark database (DE/AT/CH focus)
export const bikeparks: Bikepark[] = [
    // ─── Deutschland ───
    {
        id: 'winterberg',
        name: 'Bikepark Winterberg',
        region: 'Sauerland',
        country: '🇩🇪',
        lat: 51.1946,
        lon: 8.5338,
        website: 'https://www.bikepark-winterberg.de',
        trails: 12,
        lifts: 3,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'willingen',
        name: 'Bikepark Willingen',
        region: 'Sauerland',
        country: '🇩🇪',
        lat: 51.2900,
        lon: 8.6100,
        website: 'https://www.bikepark-willingen.de',
        trails: 7,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'warstein',
        name: 'Bikepark Warstein',
        region: 'Sauerland',
        country: '🇩🇪',
        lat: 51.4444,
        lon: 8.3500,
        website: 'https://www.bikepark-warstein.de',
        trails: 5,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'schulenberg',
        name: 'Bikepark Schulenberg',
        region: 'Harz',
        country: '🇩🇪',
        lat: 51.8494,
        lon: 10.4247,
        website: 'https://www.bikepark-schulenberg.de',
        trails: 5,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'hahnenklee',
        name: 'Bikepark Hahnenklee',
        region: 'Harz',
        country: '🇩🇪',
        lat: 51.8531,
        lon: 10.3356,
        website: 'https://www.bikepark-hahnenklee.de',
        trails: 6,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'msb-x-trail',
        name: 'MSB-X-Trail St. Andreasberg',
        region: 'Harz',
        country: '🇩🇪',
        lat: 51.7083,
        lon: 10.5139,
        website: 'https://www.msb-x-trail.de',
        trails: 4,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'braunlage',
        name: 'Bikepark Braunlage',
        region: 'Harz',
        country: '🇩🇪',
        lat: 51.7283,
        lon: 10.6089,
        website: 'https://www.bikepark-braunlage.de',
        trails: 6,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'thale',
        name: 'Bikepark Thale',
        region: 'Harz',
        country: '🇩🇪',
        lat: 51.7482,
        lon: 11.0347,
        website: 'https://www.bikepark-thale.de',
        trails: 6,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'hellental',
        name: 'Bikepark Hellental',
        region: 'Solling (bei Kassel)',
        country: '🇩🇪',
        lat: 51.7750,
        lon: 9.6000,
        website: 'https://www.bikepark-hellental.de',
        trails: 3,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'geisskopf',
        name: 'Bikepark Geisskopf',
        region: 'Bayerischer Wald',
        country: '🇩🇪',
        lat: 48.9583,
        lon: 13.2833,
        website: 'https://www.bikepark-geisskopf.de',
        trails: 8,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'osternohe',
        name: 'Bikepark Osternohe',
        region: 'Franken',
        country: '🇩🇪',
        lat: 49.5300,
        lon: 11.4300,
        website: 'https://www.bikepark-osternohe.de',
        trails: 6,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'beerfelden',
        name: 'Bikepark Beerfelden',
        region: 'Odenwald',
        country: '🇩🇪',
        lat: 49.5700,
        lon: 8.9700,
        website: 'https://www.bikepark-beerfelden.de',
        trails: 5,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'bad-wildbad',
        name: 'Bikepark Bad Wildbad',
        region: 'Schwarzwald',
        country: '🇩🇪',
        lat: 48.7500,
        lon: 8.5500,
        website: 'https://www.bikepark-bad-wildbad.de',
        trails: 8,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'todtnau',
        name: 'Bikepark Todtnau (Arena)',
        region: 'Schwarzwald',
        country: '🇩🇪',
        lat: 47.8295,
        lon: 7.9426,
        website: 'https://www.todtnau.de',
        trails: 6,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'feldberg',
        name: 'Bikepark Feldberg',
        region: 'Schwarzwald',
        country: '🇩🇪',
        lat: 47.8738,
        lon: 8.0083,
        website: 'https://www.feldberg-schwarzwald.de',
        trails: 5,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'samerberg',
        name: 'Bikepark Samerberg',
        region: 'Oberbayern',
        country: '🇩🇪',
        lat: 47.7712,
        lon: 12.2222,
        website: 'https://www.bikepark-samerberg.de',
        trails: 5,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'lenggries',
        name: 'Bikepark Lenggries',
        region: 'Oberbayern',
        country: '🇩🇪',
        lat: 47.6786,
        lon: 11.5794,
        website: 'https://www.bikepark-lenggries.com',
        trails: 7,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'garmisch',
        name: 'Bikepark Garmisch-Partenkirchen',
        region: 'Oberbayern',
        country: '🇩🇪',
        lat: 47.4917,
        lon: 11.0958,
        website: 'https://www.gapa-tourismus.de/bike',
        trails: 7,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'oberammergau',
        name: 'Bikepark Oberammergau',
        region: 'Oberbayern',
        country: '🇩🇪',
        lat: 47.5967,
        lon: 11.0681,
        website: 'https://www.bikepark-oberammergau.de',
        trails: 5,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'ilmenau',
        name: 'Bikepark Ilmenau',
        region: 'Thüringen',
        country: '🇩🇪',
        lat: 50.6870,
        lon: 10.9194,
        website: 'https://www.bikepark-ilmenau.de',
        trails: 6,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'bad-tabarz',
        name: 'Bikepark Bad Tabarz',
        region: 'Thüringen',
        country: '🇩🇪',
        lat: 50.8786,
        lon: 10.5168,
        website: 'https://www.tabarz.de',
        trails: 5,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'schoeneck',
        name: 'Bikepark Schöneck',
        region: 'Vogtland',
        country: '🇩🇪',
        lat: 50.3952,
        lon: 12.3274,
        website: 'https://www.schoeneck.info',
        trails: 4,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'oberwiesenthal',
        name: 'Bikepark Oberwiesenthal (Fichtelberg)',
        region: 'Erzgebirge',
        country: '🇩🇪',
        lat: 50.4183,
        lon: 12.9669,
        website: 'https://www.oberwiesenthal.de',
        trails: 4,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'bottrop',
        name: 'Bikepark Bottrop (Halde Norddeutschland)',
        region: 'Ruhrgebiet',
        country: '🇩🇪',
        lat: 51.5227,
        lon: 6.9464,
        website: 'https://www.bottrop.de',
        trails: 5,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    // ─── Österreich ───
    {
        id: 'leogang',
        name: 'Bikepark Leogang',
        region: 'Salzburg',
        country: '🇦🇹',
        lat: 47.4315,
        lon: 12.7631,
        website: 'https://www.bikepark-leogang.com',
        trails: 10,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'saalbach',
        name: 'Bikepark Saalbach',
        region: 'Salzburg',
        country: '🇦🇹',
        lat: 47.3917,
        lon: 12.6369,
        website: 'https://www.saalbach.com/bike',
        trails: 11,
        lifts: 3,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'schladming',
        name: 'Bikepark Planai Schladming',
        region: 'Steiermark',
        country: '🇦🇹',
        lat: 47.3939,
        lon: 13.6872,
        website: 'https://www.planai.at/bike',
        trails: 9,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'wagrain',
        name: 'Bikepark Wagrain',
        region: 'Salzburg',
        country: '🇦🇹',
        lat: 47.3333,
        lon: 13.3000,
        website: 'https://www.wagrain-kleinarl.at/bike',
        trails: 6,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'flachau',
        name: 'Bikepark Flachau',
        region: 'Salzburg',
        country: '🇦🇹',
        lat: 47.3415,
        lon: 13.3935,
        website: 'https://www.flachau.com',
        trails: 7,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'zell-am-see',
        name: 'Bikepark Zell am See (Schmittenhöhe)',
        region: 'Salzburg',
        country: '🇦🇹',
        lat: 47.3235,
        lon: 12.7985,
        website: 'https://www.schmitten.at',
        trails: 7,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'innsbruck-mutters',
        name: 'Bikepark Innsbruck (Mutters/Götzens)',
        region: 'Tirol',
        country: '🇦🇹',
        lat: 47.2333,
        lon: 11.3833,
        website: 'https://www.bikepark-innsbruck.com',
        trails: 9,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'serfaus-fiss-ladis',
        name: 'Bikepark Serfaus-Fiss-Ladis',
        region: 'Tirol',
        country: '🇦🇹',
        lat: 47.0417,
        lon: 10.6000,
        website: 'https://www.serfaus-fiss-ladis.at/bike',
        trails: 8,
        lifts: 3,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'ischgl',
        name: 'Bikepark Ischgl / Silvretta',
        region: 'Tirol',
        country: '🇦🇹',
        lat: 46.9700,
        lon: 10.2900,
        website: 'https://www.ischgl.com/bike',
        trails: 6,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'soelden',
        name: 'Bikerepublik Sölden',
        region: 'Tirol / Ötztal',
        country: '🇦🇹',
        lat: 46.9697,
        lon: 10.8764,
        website: 'https://www.soelden.com/bike',
        trails: 10,
        lifts: 3,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'obergurgl',
        name: 'Bikepark Obergurgl-Hochgurgl',
        region: 'Tirol / Ötztal',
        country: '🇦🇹',
        lat: 46.8708,
        lon: 11.0222,
        website: 'https://www.obergurgl.com',
        trails: 6,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'kirchberg',
        name: 'Bikepark Kirchberg (Spielberghaus)',
        region: 'Tirol',
        country: '🇦🇹',
        lat: 47.4500,
        lon: 12.3167,
        website: 'https://www.kitzbueheler-alpen.com/bike',
        trails: 7,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'mayrhofen',
        name: 'Bike Arena Mayrhofen',
        region: 'Zillertal',
        country: '🇦🇹',
        lat: 47.1667,
        lon: 11.8667,
        website: 'https://www.mayrhofen.at/bike',
        trails: 8,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'fieberbrunn',
        name: 'Bike Park Fieberbrunn',
        region: 'Tirol',
        country: '🇦🇹',
        lat: 47.4826,
        lon: 12.5468,
        website: 'https://www.fieberbrunn.com',
        trails: 7,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'kitzbuehel',
        name: 'Bikepark Kitzbühel (Kitzbüheler Horn)',
        region: 'Tirol',
        country: '🇦🇹',
        lat: 47.4804,
        lon: 12.4141,
        website: 'https://www.kitzbuehel.com',
        trails: 8,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'brandnertal',
        name: 'Bike Republic Brandnertal',
        region: 'Vorarlberg',
        country: '🇦🇹',
        lat: 47.1036,
        lon: 9.7377,
        website: 'https://www.brandnertal.at',
        trails: 8,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'semmering',
        name: 'Bikepark Semmering',
        region: 'Niederösterreich/Steiermark',
        country: '🇦🇹',
        lat: 47.6337,
        lon: 15.8259,
        website: 'https://www.semmering.at',
        trails: 8,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'bad-kleinkirchheim',
        name: 'Bikepark Bad Kleinkirchheim',
        region: 'Kärnten',
        country: '🇦🇹',
        lat: 46.8133,
        lon: 13.7964,
        website: 'https://www.badkleinkirchheim.at',
        trails: 6,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    // ─── Schweiz ───
    {
        id: 'lenzerheide',
        name: 'Bike Kingdom Lenzerheide',
        region: 'Graubünden',
        country: '🇨🇭',
        lat: 46.7252,
        lon: 9.5577,
        website: 'https://www.bikekingdom.ch',
        trails: 15,
        lifts: 4,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'davos',
        name: 'Bikepark Davos Klosters',
        region: 'Graubünden',
        country: '🇨🇭',
        lat: 46.8027,
        lon: 9.8361,
        website: 'https://www.davos.ch/bike',
        trails: 10,
        lifts: 3,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'brambruesch',
        name: 'Bike Park Brambrüesch (Chur)',
        region: 'Graubünden',
        country: '🇨🇭',
        lat: 46.8497,
        lon: 9.5329,
        website: 'https://www.brambruesch.ch',
        trails: 8,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'laax',
        name: 'Bike Park Laax',
        region: 'Graubünden',
        country: '🇨🇭',
        lat: 46.8287,
        lon: 9.2593,
        website: 'https://www.laax.com',
        trails: 9,
        lifts: 3,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'flumserberg',
        name: 'Bikepark Flumserberg',
        region: 'St. Gallen',
        country: '🇨🇭',
        lat: 47.0931,
        lon: 9.2896,
        website: 'https://www.flumserberg.ch',
        trails: 10,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'hasliberg',
        name: 'Bike Park Hasliberg',
        region: 'Berner Oberland',
        country: '🇨🇭',
        lat: 46.7392,
        lon: 8.2051,
        website: 'https://www.hasliberg.ch',
        trails: 7,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'engelberg',
        name: 'Bike Park Engelberg (Brunni)',
        region: 'Obwalden',
        country: '🇨🇭',
        lat: 46.8214,
        lon: 8.4058,
        website: 'https://www.engelberg.ch',
        trails: 5,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'zermatt',
        name: 'Bikepark Zermatt (Sunnegga)',
        region: 'Wallis',
        country: '🇨🇭',
        lat: 46.0217,
        lon: 7.7490,
        website: 'https://www.zermatt.ch',
        trails: 8,
        lifts: 3,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'verbier',
        name: 'Bike Park Verbier',
        region: 'Wallis',
        country: '🇨🇭',
        lat: 46.0966,
        lon: 7.2266,
        website: 'https://www.verbier.ch',
        trails: 10,
        lifts: 3,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    // ─── Frankreich / Italien / Tschechien (grenznah) ───
    {
        id: 'lac-blanc',
        name: 'Bikepark Lac Blanc',
        region: 'Elsass / Vogesen',
        country: '🇫🇷',
        lat: 48.1261,
        lon: 7.0917,
        website: 'https://www.lac-blanc.com/vtt',
        trails: 14,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'les-gets',
        name: 'Bikepark Les Gets',
        region: 'Haute-Savoie',
        country: '🇫🇷',
        lat: 46.1589,
        lon: 6.6700,
        website: 'https://www.lesgets.com/vtt',
        trails: 20,
        lifts: 5,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'mottolino',
        name: 'Mottolino Bikepark',
        region: 'Lombardei',
        country: '🇮🇹',
        lat: 46.4667,
        lon: 10.3500,
        website: 'https://www.mottolino.com/bike',
        trails: 12,
        lifts: 3,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'klinovec',
        name: 'Bikepark Klínovec (Keilberg)',
        region: 'Erzgebirge',
        country: '🇨🇿',
        lat: 50.3953,
        lon: 12.9681,
        website: 'https://www.klinovec.cz/bike',
        trails: 8,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'spicak',
        name: 'Bikepark Špičák',
        region: 'Böhmerwald',
        country: '🇨🇿',
        lat: 49.1667,
        lon: 13.3000,
        website: 'https://www.spicak.cz/bike',
        trails: 6,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'rokytnice',
        name: 'Bikepark Rokytnice nad Jizerou',
        region: 'Riesengebirge',
        country: '🇨🇿',
        lat: 50.7250,
        lon: 15.4472,
        website: 'https://www.rokytnice.com/bike',
        trails: 7,
        lifts: 2,
        liftStatus: 'unknown',
        openLifts: 0,
    },
    {
        id: 'lipno',
        name: 'Bikepark Lipno',
        region: 'Böhmerwald (Moldaustausee)',
        country: '🇨🇿',
        lat: 48.6333,
        lon: 14.2333,
        website: 'https://www.lipno.info/bike',
        trails: 5,
        lifts: 1,
        liftStatus: 'unknown',
        openLifts: 0,
    },
];
